package ssa.paymentrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ListaUnitaOrganizzativa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<ssa.paymentrequest.UnitaOrganizzativa> lista;

   public ListaUnitaOrganizzativa()
   {
   }

   public java.util.List<ssa.paymentrequest.UnitaOrganizzativa> getLista()
   {
      return this.lista;
   }

   public void setLista(
         java.util.List<ssa.paymentrequest.UnitaOrganizzativa> lista)
   {
      this.lista = lista;
   }

   public ListaUnitaOrganizzativa(
         java.util.List<ssa.paymentrequest.UnitaOrganizzativa> lista)
   {
      this.lista = lista;
   }

}